USE [DCTESTS]
GO
INSERT INTO TBPROVA (ASSUNTO, DATA, FEEDBACK_REALIZADO, GABARITO) VALUES ('ENCAPSULAMENTO', GETDATE(), 0, 'ABCDE' );

USE [DCTESTS]
GO
INSERT INTO TBALUNO (NOME) VALUES ('RECH');
INSERT INTO TBALUNO (NOME) VALUES ('GUILHERME');
INSERT INTO TBALUNO (NOME) VALUES ('WESLEY');
INSERT INTO TBALUNO (NOME) VALUES ('THIAGO');

USE [DCTESTS]
GO
INSERT INTO TBNOTA (ID_ALUNO, ID_PROVA, VALOR) VALUES (1, 1, 7);
INSERT INTO TBNOTA (ID_ALUNO, ID_PROVA, VALOR) VALUES (2, 1, 6);
INSERT INTO TBNOTA (ID_ALUNO, ID_PROVA, VALOR) VALUES (3, 1, 5);
INSERT INTO TBNOTA (ID_ALUNO, ID_PROVA, VALOR) VALUES (4, 1, 4);
