USE [DCTESTS]
GO

SELECT * FROM TBALUNO
SELECT *  FROM TBPROVA
SELECT *  FROM TBNOTA

--SELECT ID, DATA, ASSUNTO, FEEDBACK_REALIZADO, GABARITO FROM TBPROVA WHERE FEEDBACK_REALIZADO=0 AND (DATEPART(MONTH, DATA) = 9 AND DATEPART(YEAR, DATA) = 2015)

