USE [DCTESTS]
GO
/****** OBJECT:  TABLE [DBO].[TBALUNO]    SCRIPT DATE: 10/09/2015 15:36:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [DBO].[TBALUNO](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[NOME] [VARCHAR](250) NOT NULL,
 CONSTRAINT [PK_TBALUNO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** OBJECT:  TABLE [DBO].[TBNOTA]    SCRIPT DATE: 10/09/2015 15:36:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [DBO].[TBNOTA](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[ID_PROVA] [INT] NOT NULL,
	[ID_ALUNO] [INT] NOT NULL,
	[VALOR] [NUMERIC](18, 0) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** OBJECT:  TABLE [DBO].[TBPROVA]    SCRIPT DATE: 10/09/2015 15:36:43 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [DBO].[TBPROVA](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[DATA] [DATETIME2](7) NOT NULL,
	[ASSUNTO] [VARCHAR](MAX) NOT NULL,
	[FEEDBACK_REALIZADO] [BIT] NOT NULL,
	[GABARITO] [VARCHAR](50),
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [DBO].[TBNOTA]  WITH CHECK ADD  CONSTRAINT [FK_TBNOTA_TBALUNO] FOREIGN KEY([ID_ALUNO])
REFERENCES [DBO].[TBALUNO] ([ID])
GO
ALTER TABLE [DBO].[TBNOTA] CHECK CONSTRAINT [FK_TBNOTA_TBALUNO]
GO
ALTER TABLE [DBO].[TBNOTA]  WITH CHECK ADD  CONSTRAINT [FK_TBNOTA_TBPROVA] FOREIGN KEY([ID_PROVA])
REFERENCES [DBO].[TBPROVA] ([ID])
GO
ALTER TABLE [DBO].[TBNOTA] CHECK CONSTRAINT [FK_TBNOTA_TBPROVA]
GO
